import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import styles from "../styles/Home.module.css";
import Button from "react-bootstrap/Button";
import Alert from "react-bootstrap/Alert";

import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faStrava } from "@fortawesome/free-brands-svg-icons";

const Home: NextPage = () => {
  const router = useRouter();

  return (
    <div className={styles.container}>
      <Head>
        <title>Hipcamp Strava - Link Account</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container mt-5 pb-5 justify-content-center d-flex vertical-center">
        <main className="">
          {router.query.error && (
            <Alert variant="danger" className="text-center">
              🔴 An error occurred when you tried to authenticate you with
              Strava. Please try again. 🔴
            </Alert>
          )}
          <h1 className={styles.title}>Welcome to Hipcamp Strava!</h1>

          <p className={styles.description}>
            To get started, tap the button below to authenticate your Strava
            account! When you link your account, all new rides and runs that you
            create on Strava, will be auto-published to{" "}
            <span className="text-primary">#running-biking-club</span> on Slack.
          </p>

          <div className="justify-content-center d-flex">
            <Button
              className="strava-color d-flex align-items-center"
              size="lg"
              onClick={() => {
                router.push("/api/auth");
              }}
            >
              <div className="mr-5">
                <FontAwesomeIcon icon={faStrava} size={"lg"} className="mr-3" />
              </div>
              <div style={{ marginLeft: 10 }}>Login with Strava</div>
            </Button>
          </div>
        </main>
      </div>
    </div>
  );
};

export default Home;
