import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import styles from "../styles/Home.module.css";
import Button from "react-bootstrap/Button";
import Alert from "react-bootstrap/Alert";

import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faGoogle, faStrava } from "@fortawesome/free-brands-svg-icons";

import { useSession, signIn, signOut, getSession } from "next-auth/react";

export async function getServerSideProps(ctx) {
  const session = await getSession(ctx);

  if (session) {
    return {
      redirect: {
        permanent: false,
        destination: "/strava",
      },
    };
  } else {
    return {
      props: {},
    };
  }
}

const Home: NextPage = () => {
  const { data: session } = useSession();
  const router = useRouter();

  return (
    <div className={styles.container}>
      <Head>
        <title>Hipcamp Strava</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container mt-5 pb-5 justify-content-center d-flex vertical-center">
        <main className="">
          {router.query.error && (
            <Alert variant="danger" className="text-center">
              🔴 An error occurred when you tried to authenticate you with
              Strava. Please try again. 🔴
            </Alert>
          )}

          {router.query.hipcamp && (
            <Alert variant="danger" className="text-center">
              🔴 This service is only available to Hipcamp employees! 🔴
            </Alert>
          )}
          <h1 className={styles.title}>Welcome to Hipcamp Strava!</h1>

          <p className={styles.description}>
            To get started, login with your Google Hipcamp account, so we know
            you are part fo the cool kid club. After that, you'll be able to
            link your Strava account, to get the fun rolling. 🚵‍♂️🏃‍♂️
          </p>

          <div className="justify-content-center d-flex">
            <Button
              className="strava-color d-flex align-items-center"
              size="lg"
              onClick={() => {
                signIn("google", {
                  callbackUrl: `${process.env.NEXT_PUBLIC_BASE_URL}/strava`,
                });
              }}
            >
              <div className="mr-5">
                <FontAwesomeIcon icon={faGoogle} size={"lg"} className="mr-3" />
              </div>
              <div style={{ marginLeft: 10 }}>Login with Google</div>
            </Button>
          </div>
        </main>
      </div>
    </div>
  );
};

export default Home;
