import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Success: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hipcamp Strava - Success!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>🥳 You did it!</h1>

        <p className={styles.description}>
          You have a linked your Strava account to Hipcamp Run Club! Now, every
          ride or run will be shared the the{" "}
          <span className="text-primary">#running-biking-club</span> Channel in
          Slack.
        </p>
      </main>
    </div>
  );
};

export default Success;
